sudo: false

language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  - TEST_LIVE=1

services:
  - elasticsearch

before_script:
  - cpanm -n Minilla Devel::Cover::Report::Coveralls
  - sleep 10
  - curl http://localhost:9200/

script:
  minil build && perl ./Build.PL && ./Build build && cover -test -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
